# Generated by Django 3.2.7 on 2021-10-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_data',
            new_name='create_at',
        ),
    ]
